### ISSUE TITLE
about the vctk_gt_frame

### ISSUE THREAD

**Issue by SEMLLYCAT** [FYJNEVERFOLLOWS/VCTK-SIM#1]
Hello！What is the vctk_gt_frame file in sim_mix_audio? Without it, the described file will not be generated!

**Comment by FYJNEVERFOLLOWS** [comment]
Hi! Sorry about the inconvenience, now `vctk_gt_frame` folder is available, you can directly download or refer to the updated `README.md` to run the scripts I provide to VAD and label VCTK for every segment.
